notifications:
  email:
    recipients:
      - andili@kth.se
    on_success: always
    on_failure: always

language: c
dist: xenial
env:
  - CACHE_DIR=$HOME/cache PATH=$CACHE_DIR/polyml/bin:$PATH LD_LIBRARY_PATH=$CACHE_DIR/polyml/lib:$LD_LIBRARY_PATH


before_script: 
  - devel/install_poly.sh
  - devel/install_hol4.sh

script:
  - cd src && ${CACHE_DIR}/HOL/bin/Holmake


