notifications:
  email:
    recipients:
      - andili@kth.se
    on_success: always
    on_failure: always


language: c
dist: xenial
env: ENV_EXPORT_SCRIPT=devel/travis_env.sh


jobs:
  include:
    - stage: "Prepare polyml"
      before_script: devel/install_poly.sh
      script: true

#    - stage: "Prepare hol4"
#      before_script: devel/install_hol4.sh
#      script: true

    - stage: "Compilation"
      before_script: devel/install_hol4.sh
      script: devel/compile.sh


